# Gemfile-based plugins.
#
plugins:
  - jekyll-titles-from-headings
  - jekyll-optional-front-matter
  - jekyll-relative-links
  - jekyll-auto-image

# Some generic site settings. Originally used for RSS/JSON feeds. See:
#
#   https://github.com/snaptortoise/jekyll-rss-feeds
#   https://github.com/snaptortoise/jekyll-json-feeds
#
# However, these are used in some other places now, so check around
# before removing!
#
name: Cardboard Iguana Security
description: The Yak Collective is a network of over 300 independent consultants, coaches, and freelancers with varied technical and creative skills.
url: https://cardboard-iguana.com

# Default image for the auto-image plugin (used in Twitter Cards and
# Open Graph image tags.
#
image: /770a338bf8f3336b20fa14650b6f5049.webp

# Optional front-matter defaults.
#
optional_front_matter:
  remove_originals: true

# Per-page defaults.
#
defaults:
  - scope:
      path: ""
      type: pages
    values:
      layout: default
  - scope:
      path: ""
      type: posts
    values:
      layout: default

# Additional excludes.
#
exclude:
  - package.json
  - package-lock.json
  - README.md
