# Gemfile-based plugins.
#
plugins:
  - jekyll-titles-from-headings
  - jekyll-optional-front-matter
  - jekyll-relative-links
  - jekyll-readme-index

# Some generic (non-standard) site settings.
#
name: Cardboard Iguana Security
description: Cardboard Iguana Security is a weblog and digital garden focusing on cybersecurity and hacking. Interested in hiring me? Then reach out to nathan.acks@cardboard-iguana.com!
url: https://cardboard-iguana.com
icon: logo-square.webp
cover: logo-vertical.jpg
author: Nathan Acks

# Default image page (used in Twitter Cards and Open Graph image tags).
#
image: /logo-horizontal.webp

# Optional front-matter defaults.
#
optional_front_matter:
  remove_originals: true

# Readme index defaults:
readme_index:
  remove_originals: true

# Per-page defaults.
#
defaults:
  - scope:
      path: README.md
    values:
      layout: homepage
  - scope:
      path: log.md
    values:
      layout: list
  - scope:
      path: notes.md
    values:
      layout: list
  - scope:
      path: log
    values:
      layout: post
  - scope:
      path: ""
      type: pages
    values:
      layout: page
  - scope:
      path: ""
      type: posts
    values:
      layout: post

# Additional excludes.
#
exclude:
  - package.json
  - package-lock.json
